POST https://api.github.com/repos/booq-com-pl/booq-document-factory/actions/workflows/document-factory.yaml/dispatches
Accept: application/vnd.github+json
Authorization: Bearer $GITHUB_TOKEN
X-GitHub-Api-Version: 2022-11-28

{
    "ref": "main",
    "inputs": {
        "payload": "{\"employeeLastName\":\"Kowalski\",\"employeeFirstName\":\"Jan\",\"employeeBirthDate\":\"1985-03-15\",\"employeePesel\":\"85031512345\",\"employeeAddress\":\"Ulica\",\"employeePostalCode\":\"00-001\",\"employeeCity\":\"Warsaw\",\"employeeEmail\":\"adres@email.pl\",\"employeePosition\":\"Developer\",\"employerName\":\"ABC Corporation\",\"employerAddress\":\"Employer Street 1\",\"employerPostalCode\":\"00-002\",\"employerCity\":\"Warsaw\",\"userAcronym\":\"JKowalski\"}"
    }
}